# .goreleaser.yml
version: 2
project_name: extractrr

# This is the important part - tell GoReleaser not to build the binaries
builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -a
      - -tags=netgo
    ldflags:
      - -w
      - -extldflags "-static"
      - -X main.version={{ .Version }}
      - -X main.commit={{ .Commit }}
      - -X main.date={{ .CommitDate }}
    main: ./cmd/extractrr/main.go

# Use the pre-built binaries
archives:
  - id: extractrr
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

release:
  prerelease: auto
  footer: |
    **Full Changelog**: https://github.com/autobrr/extractrr/compare/{{ .PreviousTag }}...{{ .Tag }}

    ## What to do next?

    - Join our [Discord server](https://discord.gg/WQ2eUycxyT)

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
